name: Create Codespace on 42 branch creation

on:
  create:
    branches:
      - 42

jobs:
  create-codespace:
    runs-on: ubuntu-latest
    steps:
      - name: Create Codespace
        uses: microsoft/create-codespace-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config: .devcontainer.json
