name: Create Codespace on 42 branch creation

on:
  create:
    branches:
      - 42

jobs:
  create-codespace:
    runs-on: ubuntu-latest
    steps:
      - name: Create Codespace
        uses: github/codespaces-create@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          branch: ${{ github.ref }}
          config: .devcontainer.json
      - name: Checkout code
        uses: actions/checkout@v2
